In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('movies.csv',index_col=0)
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
index,,,,,,,,,,,,,,,,,,,,,
0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [3]:
len(df)

4803

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4775 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4391 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  cast                  4760 non-null   object
 21  crew                  4803 non-null   object
 22  director              4773 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 900.6+ KB

In [6]:
df[['genres', 'keywords', 'director', 'cast']].isna().sum()

genres       28
keywords    412
director     30
cast         43
dtype: int64

In [7]:
df[df[['genres', 'keywords', 'director', 'cast']].isna().any(axis=1)]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
index,,,,,,,,,,,,,,,,,,,,,
71,145000000,Adventure Action Fantasy,http://www.themummy.com/,1735,NaN,en,The Mummy: Tomb of the Dragon Emperor,"Archaeologist Rick O'Connell travels to China,...",60.034162,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,112.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,A New Evil Awakens.,The Mummy: Tomb of the Dragon Emperor,5.2,1387,Brendan Fraser Jet Li John Hannah Maria Bello ...,"[{'name': 'Ronna Kress', 'gender': 1, 'departm...",Rob Cohen
83,27000000,Action Adventure Science Fiction Romance,NaN,79698,NaN,en,The Lovers,The Lovers is an epic romance time travel adve...,2.418535,"[{""name"": ""Corsan"", ""id"": 7299}, {""name"": ""Bli...",...,109.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Love is longer than life.,The Lovers,4.8,34,Josh Hartnett Simone Kessell Tamsin Egerton Al...,"[{'name': 'Terry Ryan', 'gender': 0, 'departme...",Roland Joff\u00e9
323,100000000,Comedy Drama Romance,http://www.sexandthecitymovie.com/,37786,NaN,en,Sex and the City 2,"Carrie, Charlotte, and Miranda are all married...",18.325897,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...",...,146.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Carrie on.,Sex and the City 2,5.4,426,Sarah Jessica Parker Kristin Davis Cynthia Nix...,"[{'name': 'Sarah Jessica Parker', 'gender': 1,...",Michael Patrick King
381,90000000,Fantasy Action Family,http://www.nutcrackerin3d.com/,49852,NaN,en,The Nutcracker: The Untold Story,"Set in 1920's Vienna, this a tale of a little ...",3.593349,"[{""name"": ""Vnesheconombank"", ""id"": 24013}, {""n...",...,110.0,"[{""iso_639_1"": ""da"", ""name"": ""Dansk""}, {""iso_6...",Released,NaN,The Nutcracker: The Untold Story,5.4,50,Elle Fanning Nathan Lane John Turturro Frances...,"[{'name': 'Chris Solimine', 'gender': 0, 'depa...",Andrei Konchalovsky
436,80000000,Comedy,http://www.sonypictures.com/movies/grownups2,109418,NaN,en,Grown Ups 2,The all-star comedy cast from Grown Ups return...,45.589568,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just because they're a little older doesn't me...,Grown Ups 2,5.8,1155,Adam Sandler Kevin James Chris Rock David Spad...,"[{'name': 'Rupert Gregson-Williams', 'gender':...",Dennis Dugan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4790,0,Drama Foreign,NaN,13898,NaN,fa,دایره,Various women struggle to function in the oppr...,1.193779,"[{""name"": ""Jafar Panahi Film Productions"", ""id...",...,90.0,"[{""iso_639_1"": ""fa"", ""name"": ""\u0641\u0627\u06...",Released,NaN,The Circle,6.6,17,Nargess Mamizadeh Maryiam Palvin Almani Mojgan...,"[{'name': 'Kambuzia Partovi', 'gender': 0, 'de...",Jafar Panahi
4794,0,Thriller Horror Comedy,NaN,286939,NaN,en,Sanctuary: Quite a Conundrum,"It should have been just a normal day of sex, ...",0.166513,"[{""name"": ""Gold Lion Films"", ""id"": 37870}, {""n...",...,82.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Sanctuary: Quite a Conundrum,0.0,0,Sasha Ramos Erin Cline Emily Rogers Anthony Ru...,"[{'name': 'Thomas L. Phillips', 'gender': 0, '...",Thomas L. Phillips
4797,0,Foreign Thriller,NaN,67238,NaN,en,Cavite,"Adam, a security guard, travels from Californi...",0.022173,[],...,80.0,[],Released,NaN,Cavite,7.5,2,NaN,"[{'name': 'Neill Dela Llana', 'gender': 0, 'de...",Neill Dela Llana
4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia

In [8]:
df = df[~( (df['genres'].isna()) | (df['keywords'].isna()) | (df['director'].isna()) | (df['cast'].isna()) )]
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
index,,,,,,,,,,,,,,,,,,,,,
0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0,Drama,NaN,124606,gang audition police fake homeless actress,en,Bang,A young woman in L.A. is having a bad day: she...,0.918116,"[{""name"": ""Asylum Films"", ""id"": 10571}, {""name...",...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Sometimes you've got to break the rules,Bang,6.0,1,Darling Narita Peter Greene Michael Newland Er...,"[{'name': 'Ash Baron-Cohen', 'gender': 0, 'dep...",Ash Baron-Cohen
4796,7000,Science Fiction Drama Thriller,http://www.primermovie.com,14337,distrust garage identity crisis time travel ti...,en,Primer,Friends/fledgling entrepreneurs invent a devic...,23.307949,"[{""name"": ""Thinkfilm"", ""id"": 446}]",...,77.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What happens if it actually works?,Primer,6.9,658,Shane Carruth David Sullivan Casey Gooden Anan...,"[{'name': 'Shane Carruth', 'gender': 2, 'depar...",Shane Carruth
4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4377 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4377 non-null   int64
 1   genres                4377 non-null   object
 2   homepage              1616 non-null   object
 3   id                    4377 non-null   int64
 4   keywords              4377 non-null   object
 5   original_language     4377 non-null   object
 6   original_title        4377 non-null   object
 7   overview              4375 non-null   object
 8   popularity            4377 non-null   float64
 9   production_companies  4377 non-null   object
 10  production_countries  4377 non-null   object
 11  release_date          4377 non-null   object
 12  revenue               4377 non-null   int64
 13  runtime               4375 non-null   float64
 14  spoken_languages      4377 non-null   object
 15  status                4377 non-null   object
 16  tagline               3757 non-null   object
 17  title                 4377 non-null   object
 18  vote_average          4377 non-null   float64
 19  vote_count            4377 non-null   int64
 20  cast                  4377 non-null   object
 21  crew                  4377 non-null   object
 22  director              4377 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 820.7+ KB

In [10]:
df[['title','genres','director','cast','keywords']]

,title,genres,director,cast,keywords
index,,,,,
0,Avatar,Action Adventure Fantasy Science Fiction,James Cameron,Sam Worthington Zoe Saldana Sigourney Weaver S...,culture clash future space war space colony so...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,Gore Verbinski,Johnny Depp Orlando Bloom Keira Knightley Stel...,ocean drug abuse exotic island east india trad...
2,Spectre,Action Adventure Crime,Sam Mendes,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,spy based on novel secret agent sequel mi6
3,The Dark Knight Rises,Action Crime Drama Thriller,Christopher Nolan,Christian Bale Michael Caine Gary Oldman Anne ...,dc comics crime fighter terrorist secret ident...
4,John Carter,Action Adventure Science Fiction,Andrew Stanton,Taylor Kitsch Lynn Collins Samantha Morton Wil...,based on novel mars medallion space travel pri...
...,...,...,...,...,...
4795,Bang,Drama,Ash Baron-Cohen,Darling Narita Peter Greene Michael Newland Er...,gang audition police fake homeless actress
4796,Primer,Science Fiction Drama Thriller,Shane Carruth,Shane Carruth David Sullivan Casey Gooden Anan...,distrust garage identity crisis time travel ti...
4798,El Mariachi,Action Crime Thriller,Robert Rodriguez,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,united states\u2013mexico barrier legs arms pa...
4800,"Signed, Sealed, Delivered",Comedy Drama Romance TV Movie,Scott Smith,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,date love at first sight narration investigati...
4802,My Date with Drew,Documentary,Brian Herzlinger,Drew Barrymore Brian Herzlinger Corey Feldman ...,obsession camcorder crush dream girl